# Generated by Django 4.1.7 on 2023-07-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MADI', '0002_config_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='file',
            field=models.FileField(upload_to='MADI/IRFs'),
        ),
    ]
