# Generated by Django 4.1.7 on 2023-07-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MADI', '0003_alter_config_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='dart',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='config',
            name='mod',
            field=models.BooleanField(),
        ),
    ]
