# Generated by Django 4.1.7 on 2023-07-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MADI', '0006_alter_config_dart_alter_config_file_alter_config_mod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='dart',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='irfdata',
            name='dart',
            field=models.BooleanField(null=True),
        ),
    ]
