# Generated by Django 4.1.7 on 2023-07-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MADI', '0007_alter_config_dart_alter_irfdata_dart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='config',
            name='mod',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='irfdata',
            name='ROED',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='irfdata',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='irfdata',
            name='mod',
            field=models.BooleanField(null=True),
        ),
    ]
