# Generated by Django 4.1.7 on 2023-07-18 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MADI', '0009_remove_irfdata_file_irfdata_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='file',
        ),
    ]
